/* MIDDLWEAR — catalogue
   Prix en MAD, à l'image de la meilleure affaire dénichée chez des
   fournisseurs à travers le monde (démo, prix indicatifs).
   `perf` = indice de performance 0-100 (0 = entrée de gamme économique,
   100 = haut de gamme performance). Utilisé par le curseur Économique ⇄ Performance. */

const PRODUCTS = [
  // ───────────── ORDINATEURS ─────────────
  { id:"co-01", name:"NexBook Air 14", brand:"Nexbook", category:"ordinateurs", icon:"laptop",
    price:1900, oldPrice:4200, perf:81, condition:"reconditionne", warranty:6, specs:["14\" FHD","8 Go RAM","256 Go SSD"], rating:4.1, added:"2026-03-02",
    hw:{ kind:"pc", form:"laptop", cpu:null, ram:8, storage:256, storageType:"SSD", screen:{ size:14, res:"FHD", hz:null }, gpu:null } },
  { id:"co-02", name:"Vantix ProBook 15", brand:"Vantix", category:"ordinateurs", icon:"laptop",
    price:3600, oldPrice:8200, perf:60, condition:"reconditionne", warranty:6, specs:["15.6\" FHD","Core i5, 16 Go RAM","512 Go SSD"], badge:"Promo", rating:4.5, added:"2026-05-14",
    hw:{ kind:"pc", form:"laptop", cpu:{ brand:"Intel", tier:"i5", label:"Core i5" }, ram:16, storage:512, storageType:"SSD", screen:{ size:15.6, res:"FHD", hz:null }, gpu:null } },
  { id:"co-03", name:"Halcyon Elite X16", brand:"Halcyon", category:"ordinateurs", icon:"laptop",
    price:8900, oldPrice:18500, perf:18, condition:"reconditionne", warranty:6, specs:["16\" QHD 165Hz","Core i7, 32 Go RAM","1 To SSD + RTX"], badge:"Best-seller", rating:4.8, added:"2026-06-20",
    hw:{ kind:"pc", form:"laptop", cpu:{ brand:"Intel", tier:"i7", label:"Core i7" }, ram:32, storage:1024, storageType:"SSD", screen:{ size:16, res:"QHD", hz:165 }, gpu:"dedie" } },
  { id:"co-04", name:"Orbex Slim 13", brand:"Orbex", category:"ordinateurs", icon:"laptop",
    price:2400, oldPrice:5400, perf:46, condition:"reconditionne", warranty:6, specs:["13.3\" FHD","8 Go RAM","512 Go SSD"], rating:4.2, added:"2026-02-18",
    hw:{ kind:"pc", form:"laptop", cpu:null, ram:8, storage:512, storageType:"SSD", screen:{ size:13.3, res:"FHD", hz:null }, gpu:null } },
  { id:"co-05", name:"Kaira Tower Home", brand:"Kaira", category:"ordinateurs", icon:"desktop",
    price:2800, oldPrice:6200, perf:32, condition:"reconditionne", warranty:6, specs:["Tour compacte","16 Go RAM","512 Go SSD"], rating:4.3, added:"2026-04-09",
    hw:{ kind:"pc", form:"desktop", cpu:null, ram:16, storage:512, storageType:"SSD", gpu:null } },
  { id:"co-06", name:"Solen Compact Mini", brand:"Solen", category:"ordinateurs", icon:"desktop",
    price:1700, oldPrice:3900, perf:53, condition:"reconditionne", warranty:6, specs:["Format mini-PC","8 Go RAM","256 Go SSD"], rating:3.9, added:"2026-01-25",
    hw:{ kind:"pc", form:"desktop", cpu:null, ram:8, storage:256, storageType:"SSD", gpu:null } },
  { id:"co-07", name:"Nyra Tab 11", brand:"Nyra", category:"ordinateurs", icon:"tablet",
    price:1600, oldPrice:3600, perf:39, condition:"reconditionne", warranty:6, specs:["11\" FHD+","Stylet inclus","128 Go"], badge:"Nouveau", rating:4.4, added:"2026-07-11",
    hw:{ kind:"pc", form:"tablet", cpu:null, ram:null, storage:128, storageType:null, screen:{ size:11, res:"FHD+", hz:null }, gpu:null } },
  { id:"co-08", name:"Orbex Pad Lite", brand:"Orbex", category:"ordinateurs", icon:"tablet",
    price:890, oldPrice:2100, perf:95, condition:"reconditionne", warranty:6, specs:["10.1\" HD","4 Go RAM","64 Go"], rating:3.8, added:"2025-12-14",
    hw:{ kind:"pc", form:"tablet", cpu:null, ram:4, storage:64, storageType:null, screen:{ size:10.1, res:"HD", hz:null }, gpu:null } },
  { id:"co-09", name:"HP Pavilion 15", brand:"HP", category:"ordinateurs", icon:"laptop",
    price:2900, oldPrice:6800, perf:67, condition:"reconditionne", warranty:6, specs:["15.6\" FHD","Core i5, 8 Go RAM","512 Go SSD"], rating:4.3, added:"2026-05-28",
    hw:{ kind:"pc", form:"laptop", cpu:{ brand:"Intel", tier:"i5", label:"Core i5" }, ram:8, storage:512, storageType:"SSD", screen:{ size:15.6, res:"FHD", hz:null }, gpu:null } },
  { id:"co-10", name:"HP EliteBook 840", brand:"HP", category:"ordinateurs", icon:"laptop",
    price:3900, oldPrice:9500, perf:88, condition:"reconditionne", warranty:6, specs:["14\" FHD","Core i7, 16 Go RAM","512 Go SSD"], badge:"Best-seller", rating:4.6, added:"2026-06-30",
    hw:{ kind:"pc", form:"laptop", cpu:{ brand:"Intel", tier:"i7", label:"Core i7" }, ram:16, storage:512, storageType:"SSD", screen:{ size:14, res:"FHD", hz:null }, gpu:null } },
  { id:"co-11", name:"Dell Inspiron 15", brand:"Dell", category:"ordinateurs", icon:"laptop",
    price:2600, oldPrice:6100, perf:74, condition:"reconditionne", warranty:6, specs:["15.6\" FHD","Core i5, 8 Go RAM","256 Go SSD"], rating:4.2, added:"2026-04-15",
    hw:{ kind:"pc", form:"laptop", cpu:{ brand:"Intel", tier:"i5", label:"Core i5" }, ram:8, storage:256, storageType:"SSD", screen:{ size:15.6, res:"FHD", hz:null }, gpu:null } },
  { id:"co-12", name:"Dell XPS 13", brand:"Dell", category:"ordinateurs", icon:"laptop",
    price:5400, oldPrice:12800, perf:25, condition:"reconditionne", warranty:6, specs:["13.4\" QHD+","Core i7, 16 Go RAM","1 To SSD"], badge:"Nouveau", rating:4.8, added:"2026-07-25",
    hw:{ kind:"pc", form:"laptop", cpu:{ brand:"Intel", tier:"i7", label:"Core i7" }, ram:16, storage:1024, storageType:"SSD", screen:{ size:13.4, res:"QHD+", hz:null }, gpu:null } },

  // ───────────── CONNECTÉ ─────────────
  { id:"cn-01", name:"Halcyon Pulse Watch 5", brand:"Halcyon", category:"connecte", icon:"watch",
    price:1299, perf:69, condition:"neuf", warranty:12, specs:["AMOLED 1.9\"","ECG + SpO2","Autonomie 6 jours"], badge:"Best-seller", rating:4.7, added:"2026-06-05" },
  { id:"cn-02", name:"Vantix Chrono Lite", brand:"Vantix", category:"connecte", icon:"watch",
    price:599, perf:82, condition:"neuf", warranty:12, specs:["Écran couleur","GPS intégré","Autonomie 10 jours"], rating:4.0, added:"2026-03-19" },
  { id:"cn-03", name:"Kaira Timepiece Steel", brand:"Kaira", category:"connecte", icon:"watch",
    price:1899, oldPrice:2199, perf:50, condition:"neuf", warranty:12, specs:["Boîtier acier","Saphir anti-rayures","Paiement NFC"], badge:"Promo", rating:4.6, added:"2026-05-01" },
  { id:"cn-04", name:"Solen Fit Band 3", brand:"Solen", category:"connecte", icon:"band",
    price:279, perf:95, condition:"neuf", warranty:12, specs:["Suivi sommeil","Étanche 5 ATM","Autonomie 14 jours"], rating:4.0, added:"2026-02-22" },
  { id:"cn-05", name:"Nyra Active Band", brand:"Nyra", category:"connecte", icon:"band",
    price:349, perf:89, condition:"neuf", warranty:12, specs:["Coach IA","SpO2","Autonomie 12 jours"], badge:"Nouveau", rating:4.3, added:"2026-07-02" },
  { id:"cn-06", name:"Orbex Loop Ring", brand:"Orbex", category:"connecte", icon:"ring",
    price:1199, perf:76, condition:"neuf", warranty:12, specs:["Titane","Suivi récupération","Autonomie 7 jours"], rating:4.4, added:"2026-06-12" },
  { id:"cn-07", name:"Halcyon Aura Ring", brand:"Halcyon", category:"connecte", icon:"ring",
    price:1499, perf:57, condition:"neuf", warranty:12, specs:["Céramique","Température corporelle","Autonomie 8 jours"], badge:"Nouveau", rating:4.6, added:"2026-07-20" },
  { id:"cn-08", name:"Kaira Vision Frame", brand:"Kaira", category:"connecte", icon:"glasses",
    price:1799, perf:44, condition:"neuf", warranty:12, specs:["Audio open-ear","Anti-lumière bleue","Autonomie 5h"], rating:4.1, added:"2026-04-27" },
  { id:"cn-09", name:"Driftline Sight Glasses", brand:"Driftline", category:"connecte", icon:"glasses",
    price:1299, perf:63, condition:"neuf", warranty:12, specs:["Léger 38g","Appels mains-libres","Autonomie 4h"], rating:3.9, added:"2026-01-30" },
  { id:"cn-10", name:"Vantix Focus AR", brand:"Vantix", category:"connecte", icon:"glasses",
    price:2999, perf:37, condition:"neuf", warranty:12, specs:["Affichage AR intégré","Notifications","Autonomie 3h"], badge:"Best-seller", rating:4.5, added:"2026-06-28" },
  { id:"cn-11", name:"Samsung Galaxy Watch 6", brand:"Samsung", category:"connecte", icon:"watch",
    price:2800, perf:31, condition:"neuf", warranty:12, specs:["AMOLED 1.5\"","GPS + ECG","Autonomie 40h"], badge:"Best-seller", rating:4.6, added:"2026-06-18" },
  { id:"cn-12", name:"Apple Watch SE", brand:"Apple", category:"connecte", icon:"watch",
    price:3600, perf:24, condition:"neuf", warranty:12, specs:["Écran Retina","GPS","Autonomie 18h"], rating:4.6, added:"2026-05-09" },
  { id:"cn-13", name:"Apple Watch Series 10", brand:"Apple", category:"connecte", icon:"watch",
    price:5200, perf:18, condition:"neuf", warranty:12, specs:["AMOLED toujours actif","ECG + SpO2","Autonomie 18h"], badge:"Nouveau", rating:4.8, added:"2026-07-30" },

  // ───────────── GADGETS ─────────────
  { id:"ga-01", name:"Solen Air Buds Pro", brand:"Solen", category:"gadgets", icon:"earbuds",
    price:649, perf:51, condition:"neuf", warranty:12, specs:["Réduction de bruit active","Étanche IPX4","24h autonomie"], badge:"Promo", oldPrice:799, rating:4.6, added:"2026-05-16" },
  { id:"ga-02", name:"Kaira Sound Pods", brand:"Kaira", category:"gadgets", icon:"earbuds",
    price:249, perf:95, condition:"neuf", warranty:12, specs:["Bluetooth 5.3","Boîtier de charge","18h autonomie"], rating:4.0, added:"2026-01-09" },
  { id:"ga-03", name:"Nyra Clarity Buds", brand:"Nyra", category:"gadgets", icon:"earbuds",
    price:399, perf:73, condition:"neuf", warranty:12, specs:["Son spatial","Transparence adaptative","20h autonomie"], rating:4.3, added:"2026-04-03" },
  { id:"ga-04", name:"Vantix Orb Speaker", brand:"Vantix", category:"gadgets", icon:"speaker",
    price:549, perf:62, condition:"neuf", warranty:12, specs:["360° audio","Étanche IP67","12h autonomie"], rating:4.4, added:"2026-03-20" },
  { id:"ga-05", name:"Driftline Boom Mini", brand:"Driftline", category:"gadgets", icon:"speaker",
    price:299, perf:84, condition:"neuf", warranty:12, specs:["Compact & léger","Bluetooth 5.2","8h autonomie"], rating:3.9, added:"2025-12-22" },
  { id:"ga-06", name:"Halcyon Skyline Drone", brand:"Halcyon", category:"gadgets", icon:"drone",
    price:3499, perf:18, condition:"neuf", warranty:12, specs:["Caméra 4K stabilisée","35 min de vol","Évitement d'obstacles"], badge:"Best-seller", rating:4.8, added:"2026-06-09" },
  { id:"ga-07", name:"Orbex Scout Drone Mini", brand:"Orbex", category:"gadgets", icon:"drone",
    price:1399, perf:40, condition:"neuf", warranty:12, specs:["Caméra Full HD","Pliable","20 min de vol"], rating:4.1, added:"2026-02-15" },
  { id:"ga-08", name:"Kaira Vision VR One", brand:"Kaira", category:"gadgets", icon:"vr",
    price:2799, perf:29, condition:"neuf", warranty:12, specs:["Écran 4K par œil","Suivi des mains","Sans fil"], badge:"Nouveau", rating:4.5, added:"2026-07-03" },

  // ───────────── MOBILITÉ ─────────────
  { id:"mo-01", name:"Orbex CityHop Mini", brand:"Orbex", category:"mobilite", icon:"scooter",
    price:2399, perf:69, condition:"neuf", warranty:12, specs:["Pliable 12 kg","Autonomie 20 km","Vitesse max 20 km/h"], rating:4.0, added:"2026-02-08" },
  { id:"mo-02", name:"Driftline Urban Ride", brand:"Driftline", category:"mobilite", icon:"scooter",
    price:2999, perf:95, condition:"neuf", warranty:12, specs:["Moteur 350W","Autonomie 25 km","Vitesse max 25 km/h"], badge:"Best-seller", rating:4.5, added:"2026-05-22" },
  { id:"mo-03", name:"Vantix SwiftScoot Pro", brand:"Vantix", category:"mobilite", icon:"scooter",
    price:4999, oldPrice:5699, perf:44, condition:"neuf", warranty:12, specs:["Moteur 500W","Autonomie 45 km","Double suspension"], badge:"Promo", rating:4.6, added:"2026-06-15" },
  { id:"mo-04", name:"Halcyon TrailMax", brand:"Halcyon", category:"mobilite", icon:"scooter",
    price:7999, perf:18, condition:"neuf", warranty:12, specs:["Tout-terrain","Autonomie 55 km","Pneus 10\" tubeless"], badge:"Nouveau", rating:4.7, added:"2026-07-18" }
];
